name: '🐛 Bug Report'
description: Create a report to help us improve KeeWeb!
title: '🐛 Bug: <title>'
labels: ['Type ◦ Bug']
body:
    - type: markdown
      attributes:
          value: |
              1. Please speak `English`.
              2. Make sure you are using the latest version and take a moment to check that your issue hasn't been reported before.
              3. It's really important to provide pertinent details and logs,
                 incomplete details will be handled as an invalid report.

              <br />

    - type: dropdown
      id: priority-type
      attributes:
          label: Priority
          description: |
              How critical is the issue?
              Do not abuse this. Issues that completely break KeeWeb would be classified as critical.
              If you are requesting a new feature, then it would be **Low**
              **`Required`**
          options:
              - 'Low'
              - 'Medium'
              - 'High'
              - 'Urgent'
      validations:
          required: true

    - type: input
      id: ver-keeweb
      attributes:
          label: 'Version: KeeWeb'
          description: |
              Version of KeeWeb you are running
              Version is located in Settings › Help › App Information
              **`Required`**
          placeholder: 'Ex: v1.19.0'
      validations:
          required: true

    - type: input
      id: ver-docker
      attributes:
          label: 'Version: Docker'
          description: |
              If you are running Keeweb on docker, provide the docker version.
              Type in console `docker version`
              If you are not running Keeweb on docker; **skip**
              **`Not Required`**
          placeholder: 'Ex: v27.2.0'

    - type: dropdown
      id: host-platform
      attributes:
          label: Environment
          description: |
              How is your KeeWeb hosted?
              **`Required`**
          options:
              - 'Application'
              - 'Docker'
              - 'Web'
      validations:
          required: true

    - type: dropdown
      id: host-os
      attributes:
          label: Operating System (Build)
          description: |
              What OS is your KeeWeb running on?
              This is for users hosting Keeweb but using it from elsewhere.
              If you have Keeweb installed on Docker under Linux, but access it on Windows, your answer would be **Linux**
              **`Required`**
          options:
              - 'Android'
              - 'iOS'
              - 'Linux'
              - 'Mac'
              - 'Windows'
      validations:
          required: true

    - type: dropdown
      id: user-os
      attributes:
          label: Operating System (User)
          description: |
              What OS are you accessing KeeWeb from?
              If you have Keeweb installed on Docker under Linux, but access it on Windows, your answer would be **Windows**
              If you are running Keeweb and using it on the same machine, the above answer and this answer would be the same.
              **`Required`**
          options:
              - 'Android'
              - 'iOS'
              - 'Linux'
              - 'Mac'
              - 'Windows'
      validations:
          required: true

    - type: dropdown
      id: issue-range
      attributes:
          label: Range of issue
          description: |
              Where does this issue occur?
              Before submitting your bug report, try to see if the issue also occurs on the official demo site at https://app.keeweb.info/
              **`Required`**
          options:
              - 'Issue occurs on my own install AND demo site'
              - 'Issue occurs only on my own install, demo site works correctly'
      validations:
          required: true

    - type: dropdown
      id: issue-db-affect
      attributes:
          label: Database
          description: |
              Do different database files fix the issue?
              **`Required`**
          options:
              - 'Issue occurs only with new databases'
              - 'Issue occurs only with existing databases'
              - 'Issue occurs with both new + existing databases'
      validations:
          required: true

    - type: textarea
      id: logs-env
      attributes:
          label: Copy/Paste Environment Details
          description: |
              Copy all information from Settings › Help inside KeeWeb
              **`Required`**
          render: shell
      validations:
          required: true

    - type: textarea
      id: description
      attributes:
          label: Description
          description: |
              Please provide a description of your issue here.
              **`Required`**
      validations:
          required: true

    - type: textarea
      id: steps-reproduce
      attributes:
          label: Steps To Reproduce
          description: |
              Describe the steps that need taken by the developer(s) to get the error / issue you're experiencing.
              **`Required`**
          value: |
              1. 
              2. 
      validations:
          required: true

    - type: textarea
      id: expected-behavior
      attributes:
          label: Expected Behavior
          description: |
              What do you expect KeeWeb to actually do if it were working properly
              **`Required`**
          value: |
              - 
              - 
      validations:
          required: true

    - type: textarea
      id: logs-console
      attributes:
          label: Logs
          description: |
              List any error messages you receive in the developer console. Developer console for **web** can be opened with **SHIFT + CTRL + I**
              Open **dev tools** in your browser and attach output log from **CONSOLE** tab. If you are using a desktop app, devtools can be opened from Settings › General › Advanced.
              **`Not Required`**
          render: shell

    - type: textarea
      id: attachments
      attributes:
          label: 'Attachments'
          description: |
              Add attachments here.
              Attach a test database below if your issue is with a specific database. Ensure it has no real security information within it as it will be publicly visible to all.
              Provide screenshots of any errors or the issue you're having. Gifs are even better.
              **`Not Required`**
